apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kube-helloworld
  template:
    metadata:
      labels:
        app: kube-helloworld
    spec:
      containers:
        - name: kube-helloworld
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

